### ISSUE TITLE
Seed7 fails on ARM

### ISSUE THREAD

**Issue by mingodad** [ThomasMertes/seed7#6]
While trying to build seed7 on ARM devices (Android 32/64 bits, Pinephone 64 bits) there are several tests that fail (see attached logs) for example:
```
chkflt 
 *** The interpreted chkflt does not work okay:

Float literals work correct.
...
Conversion from integer to float works correct.
 ***** Truncation of float does not work correct. (1)
 ***** Truncation of float does not work correct. (2)
 ***** Truncation of float does not work correct.
 ***** Rounding of float does not work correct. (1)
 ***** Rounding of float does not work correct. (2)
 ***** Rounding of float does not work correct.
...
chkbin 
 *** The interpreted chkbin does not work okay:

 ***** Converting IEEE single precision float to bin32 does not work correct.
 ***** Converting IEEE double precision float to bin64 does not work correct.
Converting bin32 and bin64 values to float works correct.
```
On Android 32 bits with `termux` it doesn't build, on 64 bits it builds with warnings and also fail tests with floating point.

[make.log.zip](https://github.com/ThomasMertes/seed7/files/5757921/make.log.zip)

**Comment by ThomasMertes** [comment]
These errors have probably all the same source: The C run-time library function strtod().
This function is used by the Seed7 parser and by the Seed7 run-time library to convert a
float literal to a Seed7 float value. Seed7 uses C run-time library functions for many
purposes. The reason for that is simple. The C run-time is usually tuned for performance
and is heavily tested. The problem is that Seed7 is more strict on how certain functions
should work. Obviously strtod() from the C run-time library is not at a level that Seed7
expects. As long as Seed7 has not an own implementation of the strtod() function (that
would be used if strtod() from the C run-time is not sufficient) this problem will persist.
But basically this is not a severe problem: The float literals will just be as good as
the float literals of C. Beyond corner cases in float literals you can trust the Seed7
implementation on your Android.

**Comment by mingodad** [comment]
And what about 32 bits on ARM ?

**Comment by ThomasMertes** [comment]
I assume that make.log.zip refers to the 64-bit build. So far make.log.zip looks okay
(except for the strtod() issues mentioned above). Please provide also log information for
the 32 bit build on ARM. If make depend succeeds the file version.h would also be helpful.

**Comment by ThomasMertes** [comment]
I was able to install termux on my Android 10 phone.

- My theory that the errors are caused by the C run-time library function strtod() turned out to be wrong (the replacement strtod() that I developed in the meantime will be used for another project. :-) ). The failures in the tests are really rare corner cases as I expected.
- The build with clang (makefile mk_clang.mak) triggered several interesting findings:
1. Some X11 functions were missing in fwd_x11.c
2. It makes sense to allow the replacement of system headers (x11_x.h and fwd_term.h) in mk_clang.mak. This way compilation works also without X11 headers.
3. The warning box created by warn.c had too much width to be readable in termux. So this width has been reduced.
4. At the ARM processor casting 9223372036854775807.0 to a 64-bit integer works correct. On x86 and x64 this produces a negative number. The tests in chkflt.sd7 now check that either the correct value is returned or RANGE_ERROR is raised.
5. On the ARM processor the expression 0.0 / 0.0 produces a different NaN pattern than x86 and x64. The tests in chkbin.sd7 have been adjusted to allow that.
6. On ARM the clang option -ftrapv triggers a SIGTRAP signal (and not SIGILL or SIGABRT as gcc and clang do on x86 and x64). Changes have been done in chkccomp.c and sigutl.c to handle SIGTRAP and to raise OVERFLOW_ERROR in the signal handler.
7. On ARM / Android / termux the function sigsetjmp() does not work according to the specification. According to the specification of `int sigsetjmp(sigjmp_buf env, int savesigs);` a non-zero value of the second parameter (savesigs) triggers a save of the current signal mask. ARM / Android / termux decided that just 0 and 1 are valid values and any other value triggers a termination of the program (with SIGABRT). As I said this is not according to the specification of sigsetjmp(). The parameter `savesigs` has been changed to 1 in all usages of sigsetjmp().

All this changes are in GitHub and I tested Seed7 with two makefiles (makefile and mk_clang.mak) and all the tests pass in both cases.

I cannot test 32-bit ARM. If you have information about Seed7 on 32-bit ARM please tell me. Don't hesitate to open a new issue for 32-bit ARM if building Seed7 failed or the tests fail.

So Seed7 works on 64-bit ARM.
