### ISSUE TITLE
Restrictions of language extensions?

### ISSUE THREAD

**Issue by bardo84** [ThomasMertes/seed7#9]
(please redirect to a forum etc. if available)

Can the language be changed or extended to be closer to say, Matlab or Julia?
- end func; -> end
- mat[i][j] -> mat[i,j]

Thanks for your work!

**Comment by WraithGlade** [comment]
I *disagree* with this suggestion, especially the first point.

(1) The existing convention of always using `end control_structure_name;` makes it so that it is just as easy to read or navigate code structures forward and backwards, whereas if it was changed to just `end` then only reading forward would be as easy, which would thus cause huge harm to the readability. 

I actually love the the author had the good sense to adopt the existing convention. It is hard to find languages that have the good judgement to account for this factor of legibility and it is a huge benefit when present.

The fact that this convention is less commonly used is also *more* reason to keep it. There are too many languages that are too homogeneous and imitate each other both syntactically and semantically for no actual good reason. From a first principles standpoint **the existing control structure block ending syntax is much better**, regardless of the fact that it is less common in other languages.

(2) The suggestion to change `mat[i][j]` to `mat[i,j]` only makes sense if the underlying structure is *not* an "array of arrays". In other words, that `[i, j]` notation suggestion would only make sense for one-dimensional arrays that are wrapped over _mathematically_ to *appear* like two-dimensional arrays. Ragged arrays of arrays (arrays of pointers to other arrays) and non-ragged one-dimensional arrays that *appear* one-dimensional (1D arrays with 2D mathematical indexing) are two _very_ different underlying data structures with very different performance and memory characteristics.

Admittedly, I've only just started using the language and I haven't tested what the underlying multi-dimensional array implementation is yet, but whether or not your suggestion for indexing makes sense depends greatly on what is actually going on under the hood.

Seed7 is not Julia and is not Matlab. The programming world needs more diversity and originality, not less.

I am tired of languages being drained of color by imitating each other.

Competition requires _differences_, otherwise why would someone choose to use a different language if were designed as merely an imitation of one or more other languages?

This is also the same reason why so the search engine ecosystem has become so bad: almost all of the companies just imitate each other, which only actually causes harm because then there is much less diversity in the results and user interfaces because they all end up being too much alike. Much the same can be said of programming languages. I am particularly tired of seemingly every new programming language closely imitating the syntax and goals of Rust, which ironically (though they do it thinking it'll make them more successful) only makes me think "why then would I use it if it is just an imitation of Rust (or any other language) since in that case I'd just use the more popular language instead?"... Imitation often undermines competitive advantages. 

Whether or not a change is of any benefit in reality can only be evaluated based on *first principles* and clear thinking and pragmatism I think. I would hate it especially if the `end control_structure` syntax was removed. That is such a smartly designed and distinguishing feature of Seed7 from what I can see so far.

**Comment by bardo84** [comment]
Thanks for replying!
Now, almost 1.5 year later, I better understand.
For example, I had to write a transpiler and had to parse the various Matlab ends into end function etc.
Keep going!

**Comment by WraithGlade** [comment]
Thanks for the feedback on my comment bardo84! (PS: I'm not the author of Seed7, just another user.)

Also, congrats on writing your own transpiler! That is a very admirable accomplishment. 🥇

I've not yet myself implemented any compiler or interpreter or transpiler project but perhaps one day I will too!
